change redirect url in userscript
iv-org/documentation pull request #136
Opened 2021-08-29 17:49 UTC by Guru-25

2021-08-30 14:25 UTC, SamantazFox commented
Thanks for noticing this! However, there is no offcial instance anymore, so it could be a good idea to put a placeholder in here (like `*://<instance domain>/...`)

2021-08-30 14:53 UTC, unixfox commented
> Thanks for noticing this! However, there is no offcial instance anymore, so it could be a good idea to put a placeholder in here (like `*://<instance domain>/...`)

redirect.invidious.io could work though

2021-08-31 13:28 UTC, unixfox requested changes

2021-08-31 13:28 UTC, unixfox commented on Always-use-"local"-to-proxy-video-through-the-server-without-creating-an-account.md
> +// @match       *://*.invidious.io/watch?v=*
Switch to `redirect.invidious.io`

2021-10-03 17:06 UTC, merged