Instances rules modifications
iv-org/documentation pull request #151
Opened 2021-10-07 12:17 UTC by SamantazFox

Instances rules modification proposal as a follow-up of the discussions from #148 and #149.

The idea is to provide an ad/tracker free official list, and to clarify some other rules.

notes: it could be a good idea to also remove the 1st rule and transform it to a more meaningful note/warning saying that the newly added instances will be on a probatory period of 1 months (should be more imho) before they can be added to the official list, so we can ensure that the owner is able to keep it updated at least once a month.

2021-10-08 16:17 UTC, syeopite commented on Invidious-Instances.md
> +9. Instances MUST NOT serve ads (sponsorship links in banner are considered ads) NOR promote products.
Not a big fan of that as well but it seems to be the consensus reached in #149

2021-10-09 15:13 UTC, SamantazFox commented on Invidious-Instances.md
> +9. Instances MUST NOT serve ads (sponsorship links in banner are considered ads) NOR promote products.
> You want to disallow sponsorship completely? I'm personally not a fan in enforcing that, but I guess it's fair.

I was quite neutral about it, but as @syeopite says, it's what the majority of the current instance owners  agreed upon. And honnestly, if we forbid ads, we should forbid sponsoring too; first, to be consistent, but also to not have to bother trying to draw a line between the two.

2021-10-09 15:57 UTC, TheFrenchGhosty approved these changes

2021-10-09 15:59 UTC, TheFrenchGhosty commented on Invidious-Instances.md
> +12. Instances MUST NOT serve ads (sponsorship links in banner are considered ads) NOR promote products.
```suggestion
12. Instances MUST NOT serve ads (sponsorship links in the banner are considered ads) NOR promote products.
```

2021-10-13 19:18 UTC, syeopite requested changes
I think this should be reformatted to look more like our issue template for new instances, and less like a wall of text. This gigantic list makes it looks like we have far more rules (and in turn more controlling) then we actually do.

2021-10-28 09:35 UTC, merged