Massively enhance the Installation documentation
iv-org/documentation pull request #160
Opened 2021-11-06 13:39 UTC by TheFrenchGhosty

- Remove a ton of "fluff" for the docker deployment because it was basic information that anyone knowing docker should know
- Add a note to make the docker work if it's not behind a reverse proxy
- Explain how to deploy the development focused docker

TODO: 

- Remove the MacOS installation steps (to be discussed)
- Explain how to configure the docker
- Simplify the manual linux installation steps stuff

2021-11-07 13:41 UTC, SamantazFox requested changes

2021-11-07 13:41 UTC, SamantazFox commented on Installation.md
> +Note: This compose is made for a true "production" setup, and is made to be used to have Invidious behind a reverse proxy, if you don't want that and prefer to directly access Invidious via its port,
```suggestion
Note: This compose is made for a true "production" setup, where Invidious is behind a reverse proxy. If you prefer to directly access Invidious, replace `127.0.0.1:3000:3000` with `3000:3000` under the `ports:` section.
```

2021-11-07 13:41 UTC, SamantazFox commented on Installation.md
> +docker-compose build
`docker-compose build` is not required. `up` already builds the containers.

2021-11-07 13:41 UTC, SamantazFox commented on Installation.md
> +
Those should be removed imho.

2021-11-26 19:06 UTC, TheFrenchGhosty commented on Installation.md
> +
It's good to separate sections in markdown, we should really keep them imo, there's really no downside in having better separation between sections.

2021-11-26 19:30 UTC, TheFrenchGhosty commented on Installation.md
> +docker-compose build
Done

2021-12-19 13:27 UTC, unixfox commented on Installation.md
> +Note: Any [PaaS](https://en.wikipedia.org/wiki/Platform_as_a_service) or [SaaS](https://en.wikipedia.org/wiki/Software_as_a_service) provider/software (Heroku, YunoHost, Repli...) are unsupported, us
On most of the PaaS you can even have your account suspended.

2021-12-19 13:28 UTC, TheFrenchGhosty commented on Installation.md
> +Note: Any [PaaS](https://en.wikipedia.org/wiki/Platform_as_a_service) or [SaaS](https://en.wikipedia.org/wiki/Software_as_a_service) provider/software (Heroku, YunoHost, Repli...) are unsupported, us
@unixfox Oh? Really? It's *that bad*?

2021-12-19 14:50 UTC, unixfox commented on Installation.md
> +Note: Any [PaaS](https://en.wikipedia.org/wiki/Platform_as_a_service) or [SaaS](https://en.wikipedia.org/wiki/Software_as_a_service) provider/software (Heroku, YunoHost, Repli...) are unsupported, us
Some don't want to deal with proxies services at all.

2022-01-02 22:37 UTC, SamantazFox commented
Mind replacing `Fedora` with `Fedora / CentOS / RHEL` and adding a note in this section saying that "on RHEL-based systems, the PowerTools repository needs to be enabled with the following command (requires EPEL): `dnf config-manager --set-enabled powertools`"

2022-01-04 14:02 UTC, TheFrenchGhosty commented
@SamantazFox Since CentOS is EOL, isn't it better to use `RHEL based system (RHEL, Fedora, AlmaLinux, RockyLinux)`?

2022-01-04 16:36 UTC, SamantazFox commented
> @SamantazFox Since CentOS is EOL, isn't it better to use `RHEL based system (RHEL, Fedora, AlmaLinux, RockyLinux)`?

Yep. Though, afaik, Fedora is a different project. It's not RHEL based.

2022-01-04 16:37 UTC, SamantazFox commented on Installation.md
> +$ for i in `git rev-list --reverse --abbrev-commit $currentVersion..HEAD` ; do file=./config/migrate-scripts/migrate-db-$i.sh ; [ -f $file ] && $file ; done
Also, I'm in favor of keeping things separate. Update instructions should be in their own file.

2022-01-04 16:41 UTC, SamantazFox commented on Installation.md
> +```
Ideally, this, DB maintenance cronjobs and systemd services should be moved to a separate "Post-install configuration" file, to keep that out of the way. I'm also tempted to put the logrotate file in the main repo. What do you think?

2022-01-08 23:52 UTC, TheFrenchGhosty commented on Installation.md
> +$ shards build src/invidious.cr --release
Doesn't work:

```
Error target src/invidious.cr was not found in shard.yml.
```

(ping @SamantazFox )

2022-01-11 23:48 UTC, SamantazFox commented on Installation.md
> +$ shards build src/invidious.cr --release
Yeah, we need to make some changes first in the repo for that to work. You should probably revert for now.

2022-02-03 11:07 UTC, mhmdanas commented on Installation.md
> +Note: Any [PaaS](https://en.wikipedia.org/wiki/Platform_as_a_service) or [SaaS](https://en.wikipedia.org/wiki/Software_as_a_service) provider/software (Heroku, YunoHost, Repli...) are unsupported, us
Also:
```suggestion
Note: Any [PaaS](https://en.wikipedia.org/wiki/Platform_as_a_service) or [SaaS](https://en.wikipedia.org/wiki/Software_as_a_service) provider/software (Heroku, YunoHost, Repli...) are unsupported, use them at your own risk, they **WILL** cause problems with Invidious and might even suspend your account for "abuse" since Invidious is heavy, bandwidth intensive and technically a proxy (and most providers don't like them). If you use one and want to report an issue, please mention which one you use.
```

2022-02-15 01:48 UTC, TheFrenchGhosty commented on Installation.md
> +Note: Any [PaaS](https://en.wikipedia.org/wiki/Platform_as_a_service) or [SaaS](https://en.wikipedia.org/wiki/Software_as_a_service) provider/software (Heroku, YunoHost, Repli...) are unsupported, us
Done

2022-02-15 01:49 UTC, TheFrenchGhosty commented on Installation.md
> +---
Done

2022-02-15 01:49 UTC, TheFrenchGhosty commented on Installation.md
> +      INVIDIOUS_CONFIG: | # Follow the config/config.yml file from the main repository to know the available configuration options
Done

2022-02-15 01:54 UTC, TheFrenchGhosty commented on Installation.md
> -Here is a working Compose setup:
Done

2022-02-15 01:55 UTC, TheFrenchGhosty commented on Installation.md
> +### Docker-compose method (development)
Done

2022-02-15 01:56 UTC, TheFrenchGhosty commented on Installation.md
> -* Fedora: `sudo brew update && sudo brew install crystal-lang`
We can't guarantee that this works, and it's better to have users take time to properly deploy an instance instead of saying "If you're in a hurry do *this*"

2022-02-15 01:57 UTC, TheFrenchGhosty commented on Installation.md
> +$ sudo pacman -S base-devel librsvg postgresql
Done

2022-02-15 01:58 UTC, TheFrenchGhosty commented on Installation.md
> +$ systemctl enable --now invidious.service
User is root

2022-02-15 01:59 UTC, TheFrenchGhosty commented on Installation.md
> +$ for i in `git rev-list --reverse --abbrev-commit $currentVersion..HEAD` ; do file=./config/migrate-scripts/migrate-db-$i.sh ; [ -f $file ] && $file ; done
Done

Feel free to move the update instructions during the refactor.

2022-02-15 02:00 UTC, TheFrenchGhosty commented on Installation.md
> +```
To be discussed, open an issue please.

2022-02-15 02:02 UTC, TheFrenchGhosty commented on Installation.md
> +$ shards build src/invidious.cr --release
Done

2022-02-15 02:49 UTC, SamantazFox requested changes

2022-02-15 02:49 UTC, SamantazFox commented on Installation.md
> +chmod 0644 /etc/logrotate.d/invidious.logrotate
`tee` and `chmod` require `sudo`

2022-02-15 02:49 UTC, SamantazFox commented on Installation.md
> +RHEL based and RHEL-like system (RHEL, Fedora, AlmaLinux, RockyLinux...)
systems*

2022-02-15 02:49 UTC, SamantazFox commented on Installation.md
> +**This method build an image from source**
"This builds a docker image from source"

2022-02-15 02:49 UTC, SamantazFox commented on Installation.md
> +      # Follow the config/config.yml file from the main repository to know the available configuration options
```suggestion
        # Please read the following file for a comprehensive list of all available
        # configuration options and their associated syntax:
        # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
```

2022-02-15 15:02 UTC, TheFrenchGhosty commented on Installation.md
> +chmod 0644 /etc/logrotate.d/invidious.logrotate
It's implied that the user is root at this point.

2022-02-15 15:03 UTC, TheFrenchGhosty commented on Installation.md
> +RHEL based and RHEL-like system (RHEL, Fedora, AlmaLinux, RockyLinux...)
Done

2022-02-15 15:05 UTC, TheFrenchGhosty commented on Installation.md
> +**This method build an image from source**
I wanted to keep the same "style" between this one and the sentence used in the production method.

I just changed "image" to "Docker image" for both so that it's more clear.

2022-02-15 15:06 UTC, TheFrenchGhosty commented on Installation.md
> +      # Follow the config/config.yml file from the main repository to know the available configuration options
Done

2022-02-17 21:07 UTC, SamantazFox commented on Installation.md
> +**This method build a Docker image from source**
builds*

2022-02-17 21:11 UTC, merged