Fix typos, grammar, and broken links
iv-org/documentation pull request #176
Opened 2021-12-30 09:08 UTC by pranjalkole

2021-12-31 01:24 UTC, SamantazFox requested changes
Looks good to me, except for the `Installation.md` and `` files: can you please undo you changes on those two files? The former is being rewritten in #160, and the second is currently parsed by the instances API, which feeds the redirector, so most format changes in here can break https://redirect.invidious.io.

2021-12-31 01:24 UTC, SamantazFox commented on How-to-setup-Anti-Captcha.md
> +Do note that cryptocurrencies give a bonus of 20% for the first time you add funds and then 10% for each new recharge.
"20% for the first time": "for" can be removed

2021-12-31 05:43 UTC, pranjalkole commented
I'm not very familiar with GitHub's pull request UI, but I think commits can be squashed while merging a pull request. If so, please squash the two commits.

2021-12-31 15:58 UTC, SamantazFox approved these changes

2022-01-04 16:42 UTC, merged

2022-01-04 16:43 UTC, SamantazFox commented
Thanks for your contribution :)