Create Redirector_Setup
iv-org/documentation pull request #298
Opened 2022-10-25 22:45 UTC by MintMain21

Guidelines on setting up Redirector to act as a YouTube-Invidious extension.

2022-10-27 03:49 UTC, MintMain21 reviewed
It just occurred to me that additional rules need to be added for the https://m.youtube.com/ domain, for both video redirects with URL Parameters and general YouTube redirects (channels, homepage, etc).

2022-11-25 14:44 UTC, TheFrenchGhosty requested changes
Please use only lower-case letters in the file name + add .md

Don't use iteroni as an example instance, use a placeholder ideally `<url>`.

2022-11-25 14:44 UTC, TheFrenchGhosty commented on docs/Redirector_Setup
> +#Rule 1
You need a space between `#`and the text.

2022-11-25 14:44 UTC, TheFrenchGhosty commented on docs/Redirector_Setup
> +#Rule 2 (Note, Rule 2 is for redirecting the youtu.be domain, typically accociated with embeds)
ditto

2022-11-25 14:44 UTC, TheFrenchGhosty commented on docs/Redirector_Setup
> +#Rule 3 (Note, Rule 3 is for those who use DDG bangs or search extensions to search YouTube and would like those properly redirected to Invidious)
ditto

2022-11-25 14:44 UTC, TheFrenchGhosty commented on docs/Redirector_Setup
> +#Rule 4
ditto

2022-11-25 14:44 UTC, TheFrenchGhosty commented on docs/Redirector_Setup
> +#Rule 5
ditto

2022-11-25 14:44 UTC, TheFrenchGhosty commented on docs/Redirector_Setup
> +#Rule 6
ditto

2022-11-25 14:44 UTC, TheFrenchGhosty commented on docs/Redirector_Setup
> +#Rule 7
ditto

2022-11-25 14:44 UTC, TheFrenchGhosty commented on docs/Redirector_Setup
> +#Rule 8
ditto

2022-11-25 14:44 UTC, TheFrenchGhosty commented on docs/Redirector_Setup
> +#Rule 9
ditto

2022-11-25 18:45 UTC, MintMain21 commented
I think I addressed everything.

And I apologize for leaving the Iteroni link without replacing the domain.

2022-11-25 19:31 UTC, TheFrenchGhosty commented on docs/redirector_setup.md
> +Redirector is a Browser extension for Firefox and Chromium that can manually be configured to redirect links, such as YouTube to Invidious or Twitter to Nitter (https://github.com/zedeus/nitter/wiki/
```suggestion
Redirector is a Browser extension for Firefox and Chromium that can manually be configured to redirect links, such as YouTube to Invidious or [Twitter to Nitter](https://github.com/zedeus/nitter/wiki/Extensions#redirector)

Get redirector: [Firefox](https://addons.mozilla.org/en-US/firefox/addon/redirector/) — [Chromium-based](https://chrome.google.com/webstore/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd) — [GitHub](https://github.com/einaregilsson/Redirector)
```

2022-11-25 19:34 UTC, TheFrenchGhosty commented
I pushed some changes myself, all good now, thank you for your contribution.

2022-11-25 19:34 UTC, merged

2022-11-25 19:57 UTC, MintMain21 reviewed
Hang on, I've noticed two mistakes. 

1. In Rule 4, the asterisk in the youtube domain (*.youtube.com) isn't showing.

2. Rule 9 isn't spaced far enough from the hashtag.

Don't know if this was on my end or yours, but it seems too late for me to change it without creating a new branch.