add documentation for channel community endpoint
iv-org/documentation pull request #333
Opened 2023-01-29 18:54 UTC by ChunkyProgrammer

closes #295

2023-02-10 06:55 UTC, SamantazFox commented on docs/api/channels_endpoint.md
> +		authorThumbnails: ImageObject[],
I like that convention to describe arrays!
How would you adapt it to an array that can hold multiple data types?

2023-02-10 06:55 UTC, SamantazFox commented on docs/api/channels_endpoint.md
> +    type: "image".
```suggestion
    type: "image",
```

2023-02-10 12:32 UTC, ChunkyProgrammer commented on docs/api/channels_endpoint.md
> +Please refer to the [Community Post Attachment types](./community_post_attachment_types.md) page for more details on the attachment JSON objects used below.
Ahh, sorry, I did have a separate file for community attachment but since it's not used outside of the community api I decided to include it in the file

2023-02-10 12:36 UTC, ChunkyProgrammer commented on docs/api/channels_endpoint.md
> +		authorThumbnails: ImageObject[],
It looks like a lot people do something like:
`(string | number)[]`

(This is how typescript does arrays)

2023-02-10 12:36 UTC, ChunkyProgrammer commented on docs/api/channels_endpoint.md
> +		attachment: Image | MultiImage | Video
Sounds good

2023-02-15 06:01 UTC, ChunkyProgrammer commented
I can include info from https://github.com/iv-org/invidious/pull/3635 in this PR if that PR gets merged before this one

2023-02-19 15:28 UTC, SamantazFox commented
> I can include info from [iv-org/invidious#3635](https://github.com/iv-org/invidious/pull/3635) in this PR if that PR gets merged before this one

Yes, that's a good idea to include both ^^

2023-02-19 15:30 UTC, SamantazFox commented on docs/api/channels_endpoint.md
> +		authorThumbnails: ImageObject[],
Ok, nifty! I'll see to update the rest of the docs to use that same naming convention.

2023-03-15 21:14 UTC, SamantazFox requested changes

2023-03-15 21:14 UTC, SamantazFox commented on docs/api/channels_endpoint.md
I just noticed: can you please use quotes around field names like in the rest of the file?

2023-03-19 13:33 UTC, merged

2023-03-19 13:33 UTC, SamantazFox commented
thanks for your help :)