Update with quality_dash preference
iv-org/documentation pull request #360
Opened 2023-03-04 22:03 UTC by MintMain21

The documentation has been updated to include the quality_dash preference to enforce preferred quality using dash.

2023-04-04 15:01 UTC, TheFrenchGhosty commented
@SamantazFox Can you please review this PR, I don't know all the URL parameters.

2023-07-14 23:07 UTC, SamantazFox commented on docs/url-parameters.md
> +| `quality_dash=480`                             | always use 480p
You might add the opther qualities here (720p, 1080p, etc..)
Alternatively, you can point to the DASH quality dropdown in the preferences, or (better yet) to config option in `config.example.yml`.

2023-07-15 07:19 UTC, MintMain21 commented on docs/url-parameters.md
> +| `quality_dash=480`                             | always use 480p
I'm not sure if I should individually highlight every quality option, but I did at least add `quality_dash=worst` and clarified that any quality can be put in and it would work.

2024-06-26 08:12 UTC, unixfox requested changes

2024-06-26 08:12 UTC, unixfox commented on docs/url-parameters.md
> -| `player_style=invidious`                     | Invidious, the default
Why removing this? The parameters still exist: https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L684

2024-06-30 03:40 UTC, MintMain21 commented on docs/url-parameters.md
> -| `player_style=invidious`                     | Invidious, the default
Did I remove that? That was unintentional. I apologize.

2024-06-30 03:46 UTC, MintMain21 commented on docs/url-parameters.md
> -| `player_style=invidious`                     | Invidious, the default
Oh no, now I remember. I moved it up in the document.

2024-06-30 03:51 UTC, MintMain21 commented on docs/url-parameters.md
> -| `player_style=invidious`                     | Invidious, the default
If you think the parameter looks better on the bottom, then by all means move it back, but since the parameter for the Video Player Style is a Video Player Parameter that it belonged with the parameters for controlling video quality, subtitles, player speed etc.

2024-07-01 15:04 UTC, unixfox commented on docs/url-parameters.md
> -| `player_style=invidious`                     | Invidious, the default
Ok great, sorry I didn't see it.

2024-07-01 15:04 UTC, merged