Add some scripts
iv-org/documentation pull request #459
Opened 2023-10-24 17:34 UTC by artemislena

Trying https://github.com/iv-org/documentation/pull/458 again.

2024-01-12 12:36 UTC, unixfox commented
ping for review @TheFrenchGhosty

2024-04-18 16:43 UTC, TheFrenchGhosty requested changes

2024-04-18 16:43 UTC, TheFrenchGhosty commented on docs/register-user.md
> +You might want to disable registration in your [instance config](/configuration), but still have a quick way to manually register users upon request. To do so, first set up a separate instance that o
Add a blank line after the header please

2024-04-18 16:43 UTC, TheFrenchGhosty commented on mkdocs.yml
> +    - 'register-user.md'
Please don't make a change to this file, I'll do it myself when it's merged

2024-04-19 18:27 UTC, artemislena commented on docs/register-user.md
> +You might want to disable registration in your [instance config](/configuration), but still have a quick way to manually register users upon request. To do so, first set up a separate instance that o
T.: Done!

2024-06-26 08:13 UTC, merged

2024-06-26 08:13 UTC, unixfox commented
@TheFrenchGhosty please add to the file mkdocs.yaml: https://github.com/iv-org/documentation/pull/459#discussion_r1571079082

2024-07-01 14:46 UTC, TheFrenchGhosty commented
@unixfox done https://github.com/iv-org/documentation/commit/377e5d6e741e86f8a64af01eb1bb8b559ca97820