Document howto export subscriptions from YouTube -
iv-org/documentation pull request #55
Opened 2021-04-17 16:28 UTC by Gestas

Resolves issue #54.

2021-04-17 23:37 UTC, jtagcat requested changes
I'd suggest breaking down the long list of steps to substeps, eg (add a tab to the beginning of sub-steps)
1. export foo foo
    1. open link
    1. foo bar
1. prepare file
1. import file

Using the link, you also have to re-number. jfyi you can just have everything as `1.`, and they will be automagically numbered.

2021-04-17 23:37 UTC, jtagcat commented on Export-YouTube-subscriptions.md
> +description: Howto export YouTube channel subscription.
```suggestion
description: How to export YouTube channel subscription.
```

2021-04-17 23:37 UTC, jtagcat commented on Export-YouTube-subscriptions.md
> +5. Click "Download YouTube data"
```suggestion
2. Open https://takeout.google.com/takeout/custom/youtube?continue=https%3A%2F%2Fmyaccount.google.com%2Fyourdata%2Fyoutube%3Fhl%3Det%26authuser%3D0
```
Just use the link instead of reading, clicking, and waiting a ton.

2021-04-17 23:37 UTC, jtagcat commented on Export-YouTube-subscriptions.md
> +**This process won't work if you go directly to [Google Takeout](https://takeout.google.com/). You must enter the Takeout process via YouTube as described below.**
Change language from `won't`, `must` to `may`, `better`.

Confirmed just now, I can do this just fine via takeout.google.com.

2021-04-17 23:37 UTC, jtagcat commented on Export-YouTube-subscriptions.md
> +14. Expand the ZIP file.
Add what you end up with (what to look for, what file to upload/import); a `subscriptions.json` file.

2021-04-17 23:37 UTC, jtagcat commented on Export-YouTube-subscriptions.md
> +15. Go to Invidious, click the little gear in the upper right corner.
```suggestion
15. Go to Invidious, click the gear in the upper-right corner. 
```

2021-04-17 23:37 UTC, jtagcat commented on Export-YouTube-subscriptions.md
> +20. Choose "Import"
```suggestion
16. Scroll down and click `Import/export data`.
17. Click the `Browse` button next to `Import YouTube subscriptions`.
18. Browse to the path you expanded the ZIP file to, there should be a `Takeout` folder.
19. Open `./Takeout/YouTube and YouTube Music/subscriptions/subscriptions.json`.
20. Choose "Import".
```

2021-04-17 23:37 UTC, jtagcat commented on Export-YouTube-subscriptions.md
> +11. Click "Create export"
```suggestion
6. Click `All YouTube data included`.
7. Click `Deselect all`.
8. Choose `channel-memberships`.
9. Click `OK`.
10. Click `Next step`.
11. Click `Create export`.
```
 - Backticks, code block, is preferred due to it looking as `one button`, and not adding visual mess.
 - Stay consistent: add periods to everywhere, if they are somewhere.

2021-06-14 19:21 UTC, SamantazFox commented
Can someone with a YT account check this?

2021-06-15 09:22 UTC, jtagcat commented
I checked it on 2021-04-17, when I requested changes.

2021-08-02 17:19 UTC, kuba-orlik commented
Those instructions don't work for me - the archive contains the subscriptions, but they are in csv, not json format, and Invidious can't parse it

2021-08-02 21:33 UTC, SamantazFox commented
> Those instructions don't work for me - the archive contains the subscriptions, but they are in csv, not json format, and Invidious can't parse it

Thanks for your feedback! Do you mind sharing some extracts of that data? I personally can't access Google accounts anymore, they're blocking me x)

2021-08-03 18:12 UTC, Gestas commented
I can confirm Google has changed the format of the export from JSON to CSV. I'll work on a new process.

2021-08-03 18:23 UTC, syeopite commented
Is the bug presented on #54 still even present? I'd expect Google to have resolved the issue by now

2021-08-11 21:39 UTC, dhuschde commented
I haven't read the whole thread yet, but think, you need an example csv.
So here is mine (Language: German)
[Abos.csv](https://github.com/iv-org/documentation/files/6971542/Abos.csv)
Also, the Error in my Invidious Instance said something with K in Line one. If I change it to a J, it say's J, so it seems like Invie is able to read the file.

I host with YunoHost.

**Logs**
Title: `Unexpected char 'K' at line 1, column 1 (JSON::ParseException)`
Date: `2021-08-10T16:16:31Z`
Route: `/data_control?referer=%2Ffeed%2Fpopular`
Version: `2021.07.27-5c76cdaa @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char 'K' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from /usr/share/crystal/src/slice.cr:229:5 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:13:12 in '->'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

2021-08-11 22:27 UTC, SamantazFox commented
> I haven't read the whole thread yet, but think, you need an example csv.
> So here is mine (Language: German)
> [Abos.csv](https://github.com/iv-org/documentation/files/6971542/Abos.csv)

Thank you :)

I've heard that the data given by youtube is a zip archive. Is that right?
If yes, is that CSV the only file in it?

2021-08-11 22:57 UTC, dhuschde commented
It gives you a ZIP. You can choose which files should be in there.
There will always be a “index” which tells you where which file is and then the files. So it's always different.

2021-08-12 21:38 UTC, SamantazFox commented
> It gives you a ZIP. You can choose which files should be in there.
> There will always be a “index” which tells you where which file is and then the files. So it's always different.

Can you please provide that `index` file, too? because without it, We have no way to guess the subscriptions file name without it (especially in non-english locales)

2021-08-13 10:56 UTC, dhuschde commented
Here is my whole ZIP file: [takeout-20210810T160826Z-001.zip](https://github.com/iv-org/documentation/files/6981893/takeout-20210810T160826Z-001.zip)
It's in German again.
I also chose to only include the Subs.

2021-08-23 14:41 UTC, PaulDance requested changes
A typo and a small grammatical mistake I think.

2021-08-23 14:41 UTC, PaulDance commented on Export-YouTube-subscriptions.md
> +description: How to export YouTube channel subscription.
```suggestion
description: How to export YouTube channel subscriptions.
```

Missing `s`, right?

2021-08-23 14:41 UTC, PaulDance commented on Export-YouTube-subscriptions.md
> +1. Make sure you are signed into YouTube with the account you want to export subscriptions for.
```suggestion
1. Make sure you are signed into YouTube with the account you want to export subscriptions from. 
```

I think "from" is more correct than "for" in this context: "one exports things *from* something", and not "one exports things *for* something" as "export" could be replaced by "extract" here.

2024-11-10 21:04 UTC, closed without merging