upd: added .ip2 network control for workflows.
iv-org/documentation pull request #561
Opened 2024-05-28 19:54 UTC by ramazansancar

2024-05-29 07:52 UTC, unixfox commented
Please don't remove the return line. Just update the workflow for including i2p but don't modify the formatting.

Thank you

2024-05-29 15:12 UTC, unixfox requested changes

2024-05-29 15:12 UTC, unixfox commented on .github/workflows/add-instance-updown.yml
> -
Please don't remove the return line here.

2024-06-06 19:30 UTC, ramazansancar commented
Check pls @unixfox

2024-06-08 20:46 UTC, unixfox requested changes

2024-06-08 20:46 UTC, unixfox commented on .github/workflows/add-instance-uptimerobot.yml
Please remove the modifications for this file. We don't maintain it anymore, we keep it just in case.

2024-06-10 06:43 UTC, merged