add steps about sig_helper and potoken + depreciate gluetun guide
iv-org/documentation pull request #581
Opened 2024-08-14 22:33 UTC by unixfox

The installation guide (Docker, Linux and MacOS) has been reflected on how to setup the new tools that will solve the error message `"This helps protect our community."`.

Please read the rendered markdown here: https://github.com/iv-org/documentation/blob/sig_helper_po_token/docs/installation.md. If you are using Docker, you need to switch to the Docker tag `:master`, like so:
```
image: quay.io/invidious/invidious:master
```

Because the code is not yet ready for a stable release.

If you have any bug regarding sig_helper or generating a potoken, please open a GitHub issue on the Invidious repository. Make sure this is not a miss-configuration issue on your side, if you are unsure, please ask your question on [Matrix](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

Also, this pull request delist gluetun which is not a recommended workaround anymore. Since this is ultimately delaying the ban until YouTube detects the need to block your public IP address.

2024-08-15 08:29 UTC, fox34 commented
Can confirm, the solution is working fine for now. I will watch my instance for the next days and report any issues. Thanks a lot for the hard work, very appreciated!

2024-08-15 11:52 UTC, animegrafmays commented
confirming it is functional on youchu.be

2024-08-15 12:35 UTC, bugmaschine commented
Once again amazing work!

2024-08-15 13:22 UTC, TheFrenchGhosty requested changes

2024-08-15 13:22 UTC, TheFrenchGhosty commented on docs/installation.md
> +    version: "3"
version is deprecated, it can be removed

2024-08-15 13:23 UTC, TheFrenchGhosty commented on mkdocs.yml
> -    - 'gluetun.md'
Should be moved to an Archive section, it might be useful at a later date.

2024-08-15 14:04 UTC, unixfox commented on docs/installation.md
> +    version: "3"
We are keeping it for backward compatibilities reasons.

2024-08-15 14:05 UTC, unixfox commented on mkdocs.yml
> -    - 'gluetun.md'
It will still be accessible from github. That's what I would call "Archive".

2024-08-15 14:10 UTC, TheFrenchGhosty requested changes
Other than those minor changes, it's all good.

Tested and working

2024-08-15 14:10 UTC, TheFrenchGhosty commented on docs/installation.md
> +            visitor_data: CHANGE_ME
```suggestion
            visitor_data: CHANGE_ME
            po_token: CHANGE_ME
```

The script generates them in this order, this will makes it less confusing for users

2024-08-15 14:10 UTC, TheFrenchGhosty commented on docs/installation.md
> +            signature_server: inv_sig_helper:12999
```suggestion
            signature_server: invidious-inv_sig_helper:12999
```

Let's prefix the inv_sig_helper with "invidious" for consistency reason + helps in case another software decide to use it

2024-08-15 14:10 UTC, TheFrenchGhosty commented on docs/installation.md
> +      inv_sig_helper:
```suggestion
      invidious-inv_sig_helper:
```

Let's prefix the inv_sig_helper with "invidious" for consistency reason + helps in case another software decide to use it

2024-08-15 14:10 UTC, TheFrenchGhosty commented on docs/installation.md
> +          - invidious-db
```suggestion
        depends_on:
          - invidious-db
          - invidious-inv_sig_helper
```

Let's depend on invidious-inv_sig_helper too

2024-08-15 14:21 UTC, unixfox commented on docs/installation.md
> +          - invidious-db
this is useless at this moment because there is no healthcheck for inv_sig_helper

2024-08-15 14:23 UTC, TheFrenchGhosty commented on docs/installation.md
> +          - invidious-db
This is still useful because it makes it so invidious wont start if the sig_helper is stopped.

It's also good practice

2024-08-15 14:24 UTC, TheFrenchGhosty commented on docs/installation.md
> +            signature_server: inv_sig_helper:12999
Consistency + in case another software decide to use it

2024-08-15 14:32 UTC, unixfox commented on docs/installation.md
> +          - invidious-db
I don't think we want that. some functionality (browsing around) is better than nothing, a straight "connection refused"

2024-08-15 14:33 UTC, unixfox commented on docs/installation.md
> +            signature_server: inv_sig_helper:12999
but if another software decides to use it, then the final container name will be different.
that's the whole point of a docker compose project.

2024-08-15 15:53 UTC, ravenblackdusk commented
My private instance is working now with these changes. I'll tell you if something goes wrong.

2024-08-16 11:30 UTC, KokaKiwi commented
My semi-private instance is now working with these changes, thanks so much for the work done! 😄
Will post here if any problem arise :)

2024-08-16 11:34 UTC, manfromdownunder commented
Why is gluetun no longer needed?  If you are regularly changing the visitor_data and po_token while behind a VPN, then doesn't that make the source ip and metadata less useful as 1000's of users would be coming from the same IP with also their own visitor_data and po_token?

2024-08-16 16:43 UTC, kalipso-cyber commented
Can also confirm this is working beautifully. Thank you very much for your hard work!

2024-08-16 17:04 UTC, Pamilg9 commented
Why doesn't Piped fix?!😔

2024-08-16 20:38 UTC, mas1701 commented
I updated my semi-private instance to the current Git version including po_token/visitor data and sig_helper and so far it works beautifully again. Thanks a lot to all who made this possible.

<details>
<summary>Feel free to try this out: EU GDPR-friendly proxy-by-default instance hosted in Germany</summary>
<br>
My instance is not publicly listed, but free to use for anyone: https://tubeplay.mscs.net/<br>
<br>
It is especially made for european privacy-sensible viewers who like a GDPR-friendly (EU "General Data Protection Regulation") way to watch YouTube content. Proxy is on by default. Server located in Germany on a gigabit datacenter connection. Should work fine with IPv4 and IPv6 clients.
</details>

2024-08-16 23:33 UTC, goodtube4u commented
This worked perfectly on my locally hosted instance. Great work all!

2024-08-17 10:05 UTC, accessiblepixel commented
I've followed the instructions with my self-hosted private instance, which was again blocked today (after having a workaround-working for a while).

I'm using portainer for various reasons (I'm looking to get away) so some of the steps I had to modify and do slightly differently - but it works perfectly so far.

Excellent work Invidious Team. Thank you! Very much appreciated.

Things I had to do:
The ``init-invidious-db.sh`` file I had to use an absolute path not a relative, and the inv_sig_helper my invidious didn't find it through the name, so I had to manually specify the IP.

Included is the full config I have.

```
version: "2.4"
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    networks:
      - invidious
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - /root/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  invidious:
    image: quay.io/invidious/invidious:master
    restart: unless-stopped
    networks:
      - invidious
    mem_limit: 1024M
    cpus: 0.5

    environment:
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        check_tables: true
        signature_server: 172.19.0.3:12999
        visitor_data: GENERATED_FROM_TRUSTED_TOKEN_GENERATOR
        po_token: GENERATED_FROM_TRUSTED_TOKEN_GENERATOR
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: postgres
          port: 5432
        full_refresh: false
        https_only: true
        domain: my-domain.tld
        hmac_key: SET_AS_DOCUMENTATION
        external_port: 443
    depends_on:
      - postgres

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - invidious


volumes:
  postgresdata:

networks:
  invidious:
```

2024-08-17 11:39 UTC, animegrafmays commented
> confirming it is functional on youchu.be

looks like this method works for about two days. restarting the signature helper and rotating the  resolved trusted session tokens resolves it. I may just write a bash script to handle this on a crontab. error from the signature helper before restarting:

```
Successfully fetched player
I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
```

2024-08-17 14:09 UTC, unixfox commented
> > confirming it is functional on youchu.be
> 
> looks like this method works for about two days. restarting the signature helper and rotating the  resolved trusted session tokens resolves it. I may just write a bash script to handle this on a crontab. error from the signature helper before restarting:
> 
> ```
> Successfully fetched player
> I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> ```

https://github.com/iv-org/inv_sig_helper/issues/12

2024-08-17 17:20 UTC, techmetx11 commented
> > confirming it is functional on youchu.be
> 
> looks like this method works for about two days. restarting the signature helper and rotating the resolved trusted session tokens resolves it. I may just write a bash script to handle this on a crontab. error from the signature helper before restarting:
> 
> ```
> Successfully fetched player
> I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> ```

If this is inv_sig_helper running in TCP, this looks like whatever client (Invidious or something else in the middle) on the other end of the connection forcefully reset the connection. Are you running inv_sig_helper in a seperate server?

2024-08-18 14:37 UTC, animegrafmays commented
> > > confirming it is functional on youchu.be
> > 
> > 
> > looks like this method works for about two days. restarting the signature helper and rotating the resolved trusted session tokens resolves it. I may just write a bash script to handle this on a crontab. error from the signature helper before restarting:
> > ```
> > Successfully fetched player
> > I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> > I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> > I/O error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
> > ```
> 
> If this is inv_sig_helper running in TCP, this looks like whatever client (Invidious or something else in the middle) on the other end of the connection forcefully reset the connection. Are you running inv_sig_helper in a seperate server? (note that invidious doesn't yet respawn the connection when it unexpectedly terminates like this)

nope. same machine. happened with both ipv4 and ipv6. I am monitoring it after the changes in https://github.com/iv-org/inv_sig_helper/issues/12 and it seems to have resolved the issue

2024-08-20 14:20 UTC, johan-adriaans commented
My instance has been running smoothly with this fix since the 16th of august. I will post any issues I run in to. Thanks for your hard work!

2024-08-21 06:42 UTC, gordon-shumway-net commented
Working fine since around 2 Days.
Had some trouble to get youtube-trusted-session-generator natively (without container) up and running on Debian 12 with Python 3.11 but more on that maybe in a seperate Issue in the proper repo.
Running the container was working just fine.

Regarding the inv_sig_helper its recommended to isolate it anyway so at the moment its running with:
podman run --network=host  -p 127.0.0.1:12999:12999 quay.io/invidious/inv-sig-helper
Its running unprivileged as the same user as invidious itself... as I think about it maybe its better to have a seperate user for that... I'm gonna change that.

--network=host because in the default podman installation the inv_sig_helper container hat trouble to access the Internet through the podman created bridge. Maybe its because of v4-Only Podman Config and v6-Only Host.
network=host makes no problems but isn't optimal I think.
I'm trying to optimize that.

Just as info, Invidious itself is running natively without container.

Thanks for your work on that!
Gordon (:

2024-08-21 09:36 UTC, fjcloud commented
Hello! I'm still having same issue with : 

```
quay.io/invidious/invidious:master-arm64
```
```
$ /invidious/invidious --version
{
  "name": "invidious",
  "version": "2024.08.13-e319c35",
  "branch": "master"
}
```
```
[production] Invidious is ready to lead at http://0.0.0.0:3000
2024-08-21 09:24:29 UTC [info] jobs: running ClearExpiredItems job
2024-08-21 09:24:29 UTC [info] jobs: ClearExpiredItems done.
2024-08-21 09:26:19 UTC [info] 302 GET / 1.69ms
2024-08-21 09:26:19 UTC [info] 200 GET /feed/popular 2.37ms
2024-08-21 09:26:20 UTC [info] 200 GET /api/v1/auth/subscriptions 2.37ms
2024-08-21 09:27:33 UTC [info] 200 GET /api/v1/auth/subscriptions 2.66ms
2024-08-21 09:27:49 UTC [error] get_video: 8Pe7uOntffY : This helps protect our community. Learn more
2024-08-21 09:27:49 UTC [warn] i18n: Missing translation key "This helps protect our community. Learn more"
2024-08-21 09:27:49 UTC [info] 500 GET /watch?v=8Pe7uOntffY 53.64ms
```

2024-08-24 09:56 UTC, Happyfeet01 commented
same problem as @fjcloud 

`2024-08-24 09:53:01 UTC [error] get_video: MoUPcVt4GUA : This helps protect our community. Learn more
2024-08-24 09:53:01 UTC [warn] i18n: Missing translation key "This helps protect our community. Learn more"
2024-08-24 09:53:01 UTC [info] 500 GET /watch?v=MoUPcVt4GUA 34.03ms
2024-08-24 09:53:11 UTC [info] 200 GET /api/v1/trending 390.2ms`

2024-08-24 09:59 UTC, animegrafmays commented
> same problem as @fjcloud
> 
> ```
> 2024-08-24 09:53:01 UTC [warn] i18n: Missing translation key "This helps protect our community. Learn more"
> 2024-08-24 09:53:01 UTC [info] 500 GET /watch?v=MoUPcVt4GUA 34.03ms
> 2024-08-24 09:53:11 UTC [info] 200 GET /api/v1/trending 390.2ms```
> ```

running a public instance google eventually rate limits the IPs. for us its about 2 days of 5-6000 unique visitors. I stop the invidious service, rotate the IPv6 address, generate a new token and restart the signature service and it works again for 2 days. does not fail always starts with google rate limiting the IP and rotating and running through the process always results in a positive service for 2 days

2024-08-24 16:12 UTC, unixfox commented
@fjcloud @Happyfeet01 try to generate the tokens potoken and visitordata on another separate IP address to see if it's better. Like your home IP address.

We have had some feedback about this working for some people.

2024-08-24 16:15 UTC, unixfox commented
> > same problem as @fjcloud
> > 
> > ```
> > 2024-08-24 09:53:01 UTC [warn] i18n: Missing translation key "This helps protect our community. Learn more"
> > 2024-08-24 09:53:01 UTC [info] 500 GET /watch?v=MoUPcVt4GUA 34.03ms
> > 2024-08-24 09:53:11 UTC [info] 200 GET /api/v1/trending 390.2ms```
> > ```
> 
> running a public instance google eventually rate limits the IPs. for us its about 2 days of 5-6000 unique visitors. I stop the invidious service, rotate the IPv6 address, generate a new token and restart the signature service and it works again for 2 days. does not fail always starts with google rate limiting the IP and rotating and running through the process always results in a positive service for 2 days 

You are most likely running into another problem if you have running a public instance.

Make sure to still have smart ipv6 rotator running. And make sure to block any bot usage, we have had some report from a public instance owner of rate limits by youtube. Message related to "browse endpoint rate limit exhausted"

It was caused by bots spamming the instance.

2024-08-25 20:00 UTC, cu commented
Working for me on my private instance.

2024-08-27 11:20 UTC, WardPearce commented
Has been working mostly fine for around a week & a half for me on https://invidious.materialio.us. Recently I've had issues with videos not loading but rotating the `visitor_data` & `po_token` fixes that.

2024-08-29 19:29 UTC, auralglow commented
Also working for me on my semi-private instance. If you need a way to rotate the po_token and visitor_data automatically, here is a way:

Create a new script and take note of the path (in this example: /opt/script/refresh-inv-token.sh)
```
#!/bin/sh

tokens=$(docker run quay.io/invidious/youtube-trusted-session-generator)
po_token=$(echo "$tokens" | grep po_token | cut -d ' ' -f 2)
visitor_data=$(echo "$tokens" | grep visitor_data | cut -d ' ' -f 2)
sed -i 's/po_token.*/po_token: '"$po_token"'/g' <path_docker_compose> && \
sed -i 's/visitor_data.*/visitor_data: '"$visitor_data"'/g' <path_docker_compose>

docker compose --project-directory <path_docker_compose_folder> up -d && docker container prune -f
```
Give it execution permissions:
`chmod +x /opt/script/refresh-inv-token.sh`
Modify the crontab, to make the script run periodically at minute 0 with `crontab -e`
And add this line:
```
00 * * * * /opt/script/refresh-inv-token.sh
```
This line makes the script run every hour. If you wish to make the script run once every 2 hours or more, replace the first "*" with */X
Example for an once every 3 hours run
```
00 */3 * * * /opt/script/refresh-inv-token.sh
```

2024-08-30 15:13 UTC, auralglow commented
> Doesn't work for me on a private instance. No videos load unless I comment out `signature_server` in `INVIDIOUS_CONFIG`. This is without using `visitor_data` and `po_token` since my instance has never been blocked yet. It is unclear to me whether inv_sig_helper is required regardless of whether the instance is blocked.
> 
> inv_sig_helper output
> 
> ```
> Fetching player
> Fetching player JS URL: https://www.youtube.com/s/player/57c75fa4/player_ias.vflset/en_US/base.js
> nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
> sig code: var bCa;var TK={dQ:function(a,b){a.splice(0,b)},
> l8:function(a){a.reverse()},
> QF:function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c}};bCa=function(a){a=a.split("");TK.dQ(a,3);TK.QF(a,41);TK.l8(a,43);TK.dQ(a,2);TK.QF(a,27);TK.dQ(a,2);return a.join("")}
> Successfully fetched player
> ```

For me, the po_token/visitor_data and the signature server parameter go hand in hand, to resolve the YouTube-side checks. So, if you use inv_sig_helper, you also need the po_token and the visitor_data.

2024-08-31 15:53 UTC, doc75 commented
Working fine on my personal instance (tested with both latest and master images). Many thanks.

2024-09-02 04:32 UTC, Handrail9 commented
Will delete if this is just noise but I want to confirm this is working for me as well, it is also working with Materialious. I also wrote myself a script to use with a systemd timer that I figured I'd share to regen the tokens every 2 hours.
```
#!/bin/bash
# Run the Docker command and capture the output

output=$(sudo docker run --rm quay.io/invidious/youtube-trusted-session-generator)

# Extract visitor_data and po_token using grep and awk

visitor_data=$(echo "$output" | grep -oP 'visitor_data: \K[^ ]+')
po_token=$(echo "$output" | grep -oP 'po_token: \K[^ ]+')

# Define the path to the .env file

env_file="/optinvidious/.env"

# Check if the extraction was successful

if [[ -z "$visitor_data" || -z "$po_token" ]]; then
    echo "Failed to extract visitor_data or po_token."
    exit 1
fi

# Update the .env file

{
    # Use sed to replace the existing values or add them if they don't exist
    sed -i "s/^VISTOR_DATA=./VISTOR_DATA=$visitor_data/" "$env_file" || echo "VISTOR_DATA=$visitor_data" >> "$env_file"
    sed -i "s/^PO_TOKEN=./PO_TOKEN=$po_token/" "$env_file" || echo "PO_TOKEN=$po_token" >> "$env_file"
} 

echo "Updated .env file with new visitor_data and po_token."
sudo docker compose down invidious inv_sig_helper invidious-db
sudo docker compose up -d
```

2024-09-10 19:45 UTC, Ex0danify commented
After Working fine a few weeks using inv_sig_helper and the po/visitor token, today I was again greeted by the "This helps protect our community. Learn more ".

I tried refreshing the tokens, now I can watch a video after refreshing a bunch of times, but most of the time it takes a few refreshes. Maybe they blocked my IP somehow (using a static IPv4 that i can not change).

2024-09-10 20:26 UTC, doc75 commented
> After Working fine a few weeks using inv_sig_helper and the po/visitor token, today I was again greeted by the "This helps protect our community. Learn more ".
> 
> I tried refreshing the tokens, now I can watch a video after refreshing a bunch of times, but most of the time it takes a few refreshes. Maybe they blocked my IP somehow (using a static IPv4 that i can not change).

Same for me since today. No more video will load even with po_token and visitor-data change ;-(

2024-09-11 03:58 UTC, animegrafmays commented
this is also broken for us after rotating ipv6 and switching ipv6 /64 to a previously unused /64

2024-09-11 23:46 UTC, manfromdownunder commented
Switching back to previous gluetun/vpn solution has resolved this for my instance.

2024-09-12 09:59 UTC, mas1701 commented
Unfortunately, we seem to be back at step 1: This will help to protect our community.

Several public instances seem to be affected as well as my own. I already tried refreshing tokens and switch to alternate IPv4 or IPv6 addresses using Source NAT, nothing helps.

(At first, reloading the browser window several times helped, but it no longer works now. It seems it was only a temporary solution while YouTube was still in the process to roll-out the latest changes to their servers.)

2024-09-19 22:33 UTC, unixfox commented
A new fix has been delivered in the master docker image: https://github.com/iv-org/invidious/pull/4928

Which fixes the latest issue related to `This helps protect our community.`. Please try if it fixes the issue for you.

Reminder:
```
image: quay.io/invidious/invidious:master
```

2024-09-19 22:40 UTC, animegrafmays commented
just merged the most recent commit and it's functional on youchu.be

2024-09-20 00:08 UTC, syeopite commented
Yep unfortunately the workaround means that we cannot parse the video's published time (along with some other info) the way we currently do as that data isn't returned there anymore.

2024-09-20 21:42 UTC, mas1701 commented
With new update it worked for some hours, now I'm getting:
"Sign in to confirm you're not a bot."

2024-09-21 04:00 UTC, animegrafmays commented
> With new update it worked for some hours, now I'm getting: "Sign in to confirm you're not a bot."

this is also happening since about 6PM EST. have rotated addresses within the ipv6 /64, assigned a new one via tunnelbroker and forced ipv4 to test all of which result in the same response "Sign in to confirm you're not a bot."

2024-09-21 12:06 UTC, unixfox commented
Yes unfortunately they patch all the current workarounds.

Join our matrix or IRC to discuss more. Don't go offtopic here thank you.

2024-09-21 14:46 UTC, merged