Update supported Crystal versions in "installation.md"
iv-org/documentation pull request #583
Opened 2024-08-18 08:50 UTC by SamantazFox

Thanks to two different users that made me realise that it was out of sync with our CI test matrix (version 1.8 and before fail due to the missing `String.match!()` function in the stdlib)

2024-08-18 10:28 UTC, syeopite commented
I was already planning on bumping the version with #577 :P

2024-08-18 12:00 UTC, SamantazFox commented
Oh, my bad, I didn't see your PR D:

2024-08-18 23:28 UTC, syeopite commented on docs/installation.md
> +**Note:** Invidious currently supports the following Crystal versions: `1.9.2` / `1.10` / `1.11` / `1.12`. \
Considering iv-org/invidious#4256 should `1.9.X` be supported?

2024-08-19 20:27 UTC, SamantazFox commented on docs/installation.md
> +**Note:** Invidious currently supports the following Crystal versions: `1.9.2` / `1.10` / `1.11` / `1.12`. \
Ah, that's something I didn't consider. Though, it seems that this was fixed in 1.10? https://github.com/crystal-lang/crystal/pull/13705

2024-08-20 04:14 UTC, syeopite commented on docs/installation.md
> +**Note:** Invidious currently supports the following Crystal versions: `1.9.2` / `1.10` / `1.11` / `1.12`. \
I guess that depends on whether we consider "supporting" just meaning that Invidious can run on a particular version, or that it will run without any problems.

2024-08-24 11:49 UTC, SamantazFox commented on docs/installation.md
> +**Note:** Invidious currently supports the following Crystal versions: `1.9.2` / `1.10` / `1.11` / `1.12`. \
Hmm, true. I think we should go for the latter: "supported" means that there is no wildcards attached.

2024-08-24 18:08 UTC, syeopite commented on docs/installation.md
> +**Note:** Invidious currently supports the following Crystal versions: `1.9.2` / `1.10` / `1.11` / `1.12`. \
Sounds good to me. Can you remove `1.9`?

2024-08-24 18:10 UTC, syeopite requested changes
Can you also include patch versions in the supported Crystal versions?

Eg: `1.10.X` / `1.11.X` / `1.12.X`

2024-09-04 21:43 UTC, SamantazFox commented
@syeopite Sorry, I forgot to make that commit. Here are the requested changes!

2024-09-04 22:58 UTC, syeopite commented on docs/installation.md
> +Versions `1.13.x` should be compatible, however we did not test it.
This is a minor nitpick but could you add a blank line inbetween these lines? It feels a bit tight to read imo 
![tight](https://github.com/user-attachments/assets/8aa7c4a3-8d3b-4757-a7f3-a41c3b2fb28f)

2024-09-04 22:59 UTC, syeopite approved these changes

2024-09-04 23:03 UTC, syeopite reviewed
Github does support admonitions now, and so does `mkdocs`. So maybe we should do something like this?


> [!Warning]
> **Note:** Invidious currently supports the following Crystal versions: `1.10.x` / `1.11.x` / `1.12.x`.
>
> Versions `1.9.x` and older are incompatible because we use features only present in the newer versions.
>
> Versions `1.13.x` should be compatible, however we did not test it.

2024-09-13 22:24 UTC, merged

2024-09-13 22:52 UTC, ChunkyProgrammer commented
I dont think that the invidious ci needs to be ran for 1.9.2 if it"s not supported:
https://github.com/iv-org/invidious/blob/4782a6703819e0babfa4792892b691dd096eeac3/.github/workflows/ci.yml#L41